// Code generated by go-swagger; DO NOT EDIT.

package members

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PostMemberHandlerFunc turns a function with the right signature into a post member handler
type PostMemberHandlerFunc func(PostMemberParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostMemberHandlerFunc) Handle(params PostMemberParams) middleware.Responder {
	return fn(params)
}

// PostMemberHandler interface for that can handle valid post member params
type PostMemberHandler interface {
	Handle(PostMemberParams) middleware.Responder
}

// NewPostMember creates a new http.Handler for the post member operation
func NewPostMember(ctx *middleware.Context, handler PostMemberHandler) *PostMember {
	return &PostMember{Context: ctx, Handler: handler}
}

/*PostMember swagger:route POST /member members postMember

Adding a member with a group

*/
type PostMember struct {
	Context *middleware.Context
	Handler PostMemberHandler
}

func (o *PostMember) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostMemberParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
