// Code generated by go-swagger; DO NOT EDIT.

package groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "secret-santa/api/models"
)

// GetGroupIDOKCode is the HTTP code returned for type GetGroupIDOK
const GetGroupIDOKCode int = 200

/*GetGroupIDOK Success

swagger:response getGroupIdOK
*/
type GetGroupIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Group `json:"body,omitempty"`
}

// NewGetGroupIDOK creates GetGroupIDOK with default headers values
func NewGetGroupIDOK() *GetGroupIDOK {

	return &GetGroupIDOK{}
}

// WithPayload adds the payload to the get group Id o k response
func (o *GetGroupIDOK) WithPayload(payload *models.Group) *GetGroupIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get group Id o k response
func (o *GetGroupIDOK) SetPayload(payload *models.Group) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetGroupIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetGroupIDNotFoundCode is the HTTP code returned for type GetGroupIDNotFound
const GetGroupIDNotFoundCode int = 404

/*GetGroupIDNotFound Not found

swagger:response getGroupIdNotFound
*/
type GetGroupIDNotFound struct {
}

// NewGetGroupIDNotFound creates GetGroupIDNotFound with default headers values
func NewGetGroupIDNotFound() *GetGroupIDNotFound {

	return &GetGroupIDNotFound{}
}

// WriteResponse to the client
func (o *GetGroupIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
