// Code generated by go-swagger; DO NOT EDIT.

package groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PostGroupHandlerFunc turns a function with the right signature into a post group handler
type PostGroupHandlerFunc func(PostGroupParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostGroupHandlerFunc) Handle(params PostGroupParams) middleware.Responder {
	return fn(params)
}

// PostGroupHandler interface for that can handle valid post group params
type PostGroupHandler interface {
	Handle(PostGroupParams) middleware.Responder
}

// NewPostGroup creates a new http.Handler for the post group operation
func NewPostGroup(ctx *middleware.Context, handler PostGroupHandler) *PostGroup {
	return &PostGroup{Context: ctx, Handler: handler}
}

/*PostGroup swagger:route POST /group groups postGroup

Add a new group

*/
type PostGroup struct {
	Context *middleware.Context
	Handler PostGroupHandler
}

func (o *PostGroup) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostGroupParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
