// Code generated by go-swagger; DO NOT EDIT.

package groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostGroupOKCode is the HTTP code returned for type PostGroupOK
const PostGroupOKCode int = 200

/*PostGroupOK Great

swagger:response postGroupOK
*/
type PostGroupOK struct {
}

// NewPostGroupOK creates PostGroupOK with default headers values
func NewPostGroupOK() *PostGroupOK {

	return &PostGroupOK{}
}

// WriteResponse to the client
func (o *PostGroupOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// PostGroupMethodNotAllowedCode is the HTTP code returned for type PostGroupMethodNotAllowed
const PostGroupMethodNotAllowedCode int = 405

/*PostGroupMethodNotAllowed Invalid input

swagger:response postGroupMethodNotAllowed
*/
type PostGroupMethodNotAllowed struct {
}

// NewPostGroupMethodNotAllowed creates PostGroupMethodNotAllowed with default headers values
func NewPostGroupMethodNotAllowed() *PostGroupMethodNotAllowed {

	return &PostGroupMethodNotAllowed{}
}

// WriteResponse to the client
func (o *PostGroupMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(405)
}
