swagger: "2.0"
info:
  version: "1.0.0"
  title: "Secret Santa"
basePath: "/v1"
schemes:
- "http"
paths:
  /group:
    post:
      tags:
      - "groups"
      summary: "Add a new group"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Group Object"
        required: true
        schema:
          $ref: "#/definitions/Group"
      responses:
        200:
          description: "Great"
        405:
          description: "Invalid input"
  
  /group/{id}:
    get:
      tags:
        - "groups"
      summary: "Gets a groups info"
      parameters:
      - name: id
        in: path
        description: Group Id
        required: true
        type: string
      responses:
        200:
          description: Success
          schema:
            $ref: "#/definitions/Group"
        404:
          description: Not found

  /member:
    post:
      tags:
        - "members"
      summary: "Adding a member with a group"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: member
        in: body
        required: true
        schema:
            $ref: "#/definitions/Member"
      responses:
        200:
          description: Success
          schema:
            $ref: "#/definitions/Member"
        400:
          description: Bad Request
    
    # get:
    #   tags:
    #   - "members"
    #   summary: "Get members with parameters"
    #   consumes:
    #   - "application/json"
    #   produces:
    #   - "application/json"
    #   parameters:
    #   - name: param
    #     in: body
    #     schema:
    #       type: object
    #       properties:
    #         id:
    #           type: string
    #         groupID:
    #           type: string
    #   responses:
    #     '200':
    #       description: Success
  

definitions:
 
  Group:
    type: "object"
    required:
    - "id"
    - "deadline"
    - "exchangeDate"
    - "moneyLimit"
    properties:
      id:
        type: "integer"
        format: "int64"
      deadline:
        type: "string"
      exchangeDate:
        type: "string"
      moneyLimit:
        type: "number"
      
  Member:
    type: "object"
    properties:
      name:
        type: string
      email:
        type: string
      spouse:
        type: string
      group:
        type: string
        
        
        
        